DROP DATABASE IF EXISTS gamewebshop;

CREATE DATABASE gamewebshop;

USE gamewebshop;


CREATE TABLE `accounts` ( 
    `ID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    `username` VARCHAR(80) NOT NULL, 
    `pass` VARCHAR(80) NOT NULL, 
    `Fname` VARCHAR(80) NULL, 
    `Lname` VARCHAR(80) NULL, 
    `email` VARCHAR(80) NOT NULL,  
    `description` TEXT NULL,
    `usertype` VARCHAR(50) DEFAULT 'user');

CREATE TABLE `product` (
	`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `img` VARCHAR(255) NOT NULL,
	`Title` VARCHAR(250) NOT NULL,
	`Price` DECIMAL(5,2) NOT NULL,
	`ReleaseDate` DATE NOT NULL,
	`Description` TEXT NOT NULL DEFAULT 'No Description',
	`Rating` DECIMAL(3,1),
	`Platform` VARCHAR(50) NOT NULL,
    `Trailer` VARCHAR (255) NOT NULL,
    `Screenshots` TEXT NOT NULL);

INSERT INTO product 
    (id, img, Title, Price, ReleaseDate, Description, Rating, Platform, Trailer, Screenshots) 
VALUES 
    (1, 'https://upload.wikimedia.org/wikipedia/en/b/b6/Ghost_of_Tsushima.jpg, https://gameranx.com/wp-content/uploads/2020/07/ghost-ost-featured.jpg', 'Ghost Of Tsushima', 445, '2020-07-17', 'Uncover the hidden wonders of Tsushima in this open-world action adventure from Sucker Punch Productions and PlayStation Studios, available for PS5 and PS4. Forge a new path and wage an unconventional war for the freedom of Tsushima. Challenge opponents with your katana, master the bow to eliminate distant threats, develop stealth tactics to ambush enemies and explore a new story on Iki Island.', 9.5, 'PS4/PS5', 'https://www.youtube.com/embed/b_iU_gnn28U', 'https://thecenturionreport.com/wp-content/uploads/2021/08/find-all-the-hot-springs.jpeg, https://robinsgames.com/wp-content/uploads/2020/11/Ghost-of-Tsushima-Review-Summary-of-the-Ghost-of-Tsushima-game-plot.jpg, https://i.guim.co.uk/img/media/c39bf8486b167ff4d297f4db15efe4e18078df98/683_269_2713_1628/master/2713.jpg?width=1200&quality=85&auto=format&fit=max&s=1134351c5ddce61338e3b3fb673166a6'),
    (2, 'https://i1.sndcdn.com/artworks-000117752385-zhasx1-t500x500.jpg, https://image.api.playstation.com/vulcan/img/rnd/202010/2614/O2Z66UWrZH8zcejxopwWxhGu.png', 'Bloodborne', 225, '2015-03-24', 'Hunt your nightmares as you search for answers in the ancient city of Yharnam, now cursed with a strange endemic illness spreading through the streets like wildfire. Danger, death and madness lurk around every corner of this dark and horrific world, and you must discover its darkest secrets in order to survive.', 10, 'PS4/PS5', 'https://www.youtube.com/embed/G203e1HhixY', 'https://img.redbull.com/images/c_fill,w_1500,h_1000,g_auto,f_auto,q_auto/redbullcom/2015/03/03/1331709128868_2/bloodborne, https://media.wired.com/photos/5955c1dc5992c54331ac192f/master/pass/bloodborne_the_old_hunters_V2.jpg'),
    (3, 'https://i1.sndcdn.com/artworks-000655287109-o7nxm0-t500x500.jpg, https://i.ytimg.com/vi/Sm7UlgK5HOw/maxresdefault.jpg', 'Outer Wilds', 240, '2019-05-28', 'Welcome to the Space Program! You are the newest recruit of Outer Wilds Ventures, a fledgling space program searching for answers in a strange, constantly evolving solar system.', 10, 'PS4/XBOX ONE/Nintendo/PC','https://www.youtube.com/embed/KYlpUxFbgTM',  'https://www.pcinvasion.com/wp-content/uploads/2019/05/outer-wilds-1-1200x675.jpg, https://cdn.pastemagazine.com/www/articles/2019/05/31/outer%20wilds%20feature%20m%20ain.jpg, https://sm.ign.com/ign_nordic/news/o/outer-wild/outer-wilds-is-coming-to-switch_yhkx.jpg'),
    (4, 'https://www.mobygames.com/images/covers/l/662249-bioshock-remastered-nintendo-switch-front-cover.jpg, https://cdn02.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_BioshockRemastered.jpg', 'Bioshock', 190, '2007-08-21', 'BioShock is a shooter unlike any you have ever played, loaded with weapons and tactics never seen. You will have a complete arsenal at your disposal from simple revolvers to grenade launchers and chemical throwers, but you will also be forced to genetically modify your DNA to create an even more deadly weapon: you. Injectable plasmids give you super human powers: blast electrical currents into water to electrocute multiple enemies, or freeze them solid and obliterate them with the swing of a wrench. No encounter ever plays out the same, and no two gamers will play the game the same way.', 8.6, 'PS3/PS4/PC/XBOX 360/XBOX ONE','https://www.youtube.com/embed/_KVfPMSK8hA', 'https://cdn.vox-cdn.com/thumbor/88lmW_GOa15KgdwJzKoHKVXmGRE=/0x0:1280x720/1200x800/filters:focal(538x258:742x462)/cdn.vox-cdn.com/uploads/chorus_image/image/66917458/bioshock_the_collection_switch_screenshot02.0.jpg, https://cdn.mos.cms.futurecdn.net/d4132487bf648572736e71934de13be7.jpg'),
    (5, 'https://upload.wikimedia.org/wikipedia/en/3/35/Far_cry_6_cover.jpg, https://images.eurogamer.net/2021/articles/2021-10-07-14-29/far_cry_6_lead.jpg', 'Far Cry 6', 460, '2021-10-06', 'Welcome to Yara, a tropical paradise frozen in time. As the dictator of Yara, Antón Castillo is intent on restoring his nation back to its former glory by any means, with his son, Diego, following in his bloody footsteps. Their oppressive rule has ignited a revolution.', 3.4, 'PS4/PS5/XBOX ONE/XBOX SERIES X/PC','https://www.youtube.com/embed/-IJuKT1mHO8', 'https://gmedia.playstation.com/is/image/SIEPDC/far-cry-6-comeback-shredder-screen-01-ps4-ps5-en-30jun21?$native$, https://assets2.rockpapershotgun.com/far-cry-6-crossbow-and-crocs.jpg/BROK/resize/1920x1920%3E/format/jpg/quality/80/far-cry-6-crossbow-and-crocs.jpg'),
    (6, 'https://s2.gaming-cdn.com/images/products/6202/orig/spil-steam-horizon-zero-dawn-complete-edition-cover.jpg, https://image.api.playstation.com/vulcan/ap/rnd/202010/0221/1jE1dG7sSfbJnhoRfAeVc2rs.png?w=1024', 'Horizon Zero Dawn', 150, '2017-02-28', 'In an era where Machines roam the land and mankind is no longer the dominant species, a young hunter named Aloy embarks on a journey to discover her destiny. In a lush, post-apocalyptic world where nature has reclaimed the ruins of a forgotten civilization, pockets of humanity live on in primitive hunter-gatherer tribes. Their dominion over the new wilderness has been usurped by the Machines – fearsome mechanical creatures of unknown origin.', 8.4, 'PS4/PS5','https://www.youtube.com/embed/u4-FCsiF5x4', 'https://cdn.vox-cdn.com/thumbor/Qxdbz7ojsJMqKYcL8SLS9T8oXTk=/0x0:1920x1080/1200x800/filters:focal(807x387:1113x693)/cdn.vox-cdn.com/uploads/chorus_image/image/68982682/Aiming_at_Thunderjaw.0.0.png, https://variety.com/wp-content/uploads/2019/03/hzdaloy.jpeg, https://images0.persgroep.net/rcs/GvJrsEQ6TjdoOZ67v9K6cVpiM7k/diocontent/128897753/_focus/0.29/0.63/_fill/1200/630/?appId=21791a8992982cd8da851550a453bd7f&quality=0.7'),
    (7, 'https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/f8dc3073b73dfb018693b7a1dbfcef43.png, https://thepromotiontime.com/wp-content/uploads/2021/01/H2x1_NSwitch_RiskOfRain2_image1600w.jpg', 'Risk of Rain 2', 185, '2020-08-11', 'SURVIVE AN ALIEN PLANET! Over a dozen handcrafted locales await, each packed with challenging monsters and enormous bosses that oppose your continued existence. Fight your way to the final boss and escape or continue your run indefinitely to see just how long you can survive. A unique scaling system means both you and your foes limitlessly increase in power over the course of a game.', 9, 'PS4/XBOX ONE/Nintendo/PC','https://www.youtube.com/embed/pJ-aR--gScM', 'https://gamingbolt.com/wp-content/uploads/2020/08/risk-of-rain-2-image-4.jpg, https://image.jeuxvideo.com/medias-md/159828/1598279048-1030-capture-d-ecran.png'),
    (8, 'https://direct.rhapsody.com/imageserver/images/alb.482944940/500x500.jpg, https://cdn.mos.cms.futurecdn.net/CEajpQcrXWZQHMMDqoF3zF.jpeg', 'The Last Of Us 2', 445, '2020-06-19', ' Five years after their dangerous journey across the post-pandemic United States, Ellie and Joel have settled down in Jackson, Wyoming. Living amongst a thriving community of survivors has allowed them peace and stability, despite the constant threat of the infected and other, more desperate survivors. When a violent event disrupts that peace, Ellie embarks on a relentless journey to carry out justice and find closure. As she hunts those responsible one by one, she is confronted with the devastating physical and emotional repercussions of her actions.', 5.7, 'PS4/PS5','https://www.youtube.com/embed/vhII1qlcZ4E', 'https://sm.ign.com/ign_nordic/news/t/the-last-o/the-last-of-us-part-2-is-getting-a-ps5-exclusive-performance_s43z.jpg, https://media.npr.org/assets/img/2021/02/25/2510225ed61038a780b9.08969556-tloupii_preview_screenshot_04_wide-933bf2d68d635cd07832685ab3b2ed887e1d249e.jpg, https://media.wired.com/photos/5edfe6ec39276c283696879a/master/pass/culture_tlou2_1.jpg');




















-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (2, 'Grudge 2, The', 184.75, '2018-12-23', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 5.1, 'Honda');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (3, 'Hamster Factor and Other Tales of Twelve Monkeys, The', 117.1, '2016-11-13', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 7.5, 'Toyota');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (4, 'Black God, White Devil (Deus e o Diabo na Terra do Sol)', 66.52, '2011-05-30', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 9.0, 'Buick');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (5, 'Gorilla, The', 335.78, '2017-07-08', 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 5.0, 'Mercedes-Benz');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (6, '200 M.P.H.', 265.39, '2013-09-20', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 9.2, 'Ford');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (7, 'Rat Race', 295.39, '2012-12-07', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 7.2, 'Mazda');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (8, 'Cthulhu', 225.31, '2015-11-28', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 9.7, 'GMC');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (9, 'Batman: Under the Red Hood', 276.94, '2011-06-09', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 2.6, 'Nissan');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (10, 'Three (a.k.a. 3)', 174.13, '2021-09-30', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 8.5, 'Subaru');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (11, 'Lemora: A Child''s Tale of the Supernatural', 163.92, '2011-01-26', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 7.5, 'Toyota');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (12, 'Marriage Made in Heaven, A (Rab Ne Bana Di Jodi)', 97.58, '2017-02-16', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 5.4, 'Ford');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (13, 'Dragon Gate Inn (Dragon Inn) (Long men kezhan)', 327.11, '2012-04-28', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 4.3, 'Oldsmobile');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (14, 'Grand, The', 124.23, '2016-04-05', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 6.6, 'Cadillac');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (15, 'Snakehead Terror', 91.11, '2018-02-10', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1.6, 'Nissan');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (16, 'Club Fed', 193.66, '2020-05-15', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 8.6, 'BMW');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (17, 'Meteor', 340.67, '2019-06-02', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 4.3, 'Subaru');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (18, 'Lost Boys: The Tribe', 40.82, '2020-01-28', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 9.3, 'Pontiac');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (19, 'Pittsburgh', 393.91, '2011-10-15', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 1.4, 'Chevrolet');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (20, 'School Daze', 260.05, '2013-04-17', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 6.2, 'Toyota');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (21, 'American Pie Presents The Naked Mile (American Pie 5: The Naked Mile)', 98.02, '2020-12-08', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 2.3, 'Pontiac');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (22, 'Elevator ', 209.75, '2011-03-08', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 2.7, 'Buick');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (23, 'Never Die Alone', 142.11, '2017-11-28', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 5.4, 'Subaru');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (24, 'Requiem for a Dream', 325.22, '2012-02-16', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 3.6, 'Ford');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (25, 'Or (a.k.a. My Treasure)', 151.74, '2017-11-15', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 3.9, 'Land Rover');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (26, 'Dancing Outlaw II: Jesco Goes to Hollywood', 291.8, '2014-11-22', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 6.0, 'Ford');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (27, 'Too Many Girls', 217.6, '2021-07-04', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 2.1, 'Pontiac');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (28, 'Cochochi', 157.95, '2019-05-19', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 6.3, 'Subaru');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (29, 'Evening with Kevin Smith, An', 139.51, '2020-02-23', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 2.0, 'Mazda');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (30, 'House Party 2', 192.4, '2010-08-25', 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 8.7, 'Saab');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (31, 'Cry, the Beloved Country', 123.51, '2018-01-26', 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 8.1, 'GMC');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (32, 'Best of the Best 2', 344.49, '2011-02-21', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 6.3, 'Pontiac');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (33, 'Faster Pussycat! Kill! Kill!', 293.54, '2011-11-29', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 3.2, 'Isuzu');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (34, 'Jar City (Mýrin)', 330.02, '2014-08-09', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 4.9, 'Audi');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (35, 'Dawn of the Dead', 119.18, '2017-11-25', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 8.3, 'Toyota');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (36, 'Julius Caesar', 341.71, '2013-08-10', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1.4, 'Kia');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (37, 'Fifty Pills', 326.47, '2019-05-01', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 8.4, 'Ferrari');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (38, 'One Point O', 152.78, '2020-07-29', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 5.8, 'Saab');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (39, 'Talhotblond:', 218.44, '2015-03-31', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 6.1, 'Mitsubishi');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (40, 'Shadow Puppets', 304.33, '2017-08-02', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 6.1, 'Ford');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (41, '588 Rue Paradis (Mother)', 82.89, '2013-07-04', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 3.7, 'Volvo');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (42, 'Cabin Boy', 114.34, '2015-11-16', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 5.9, 'Mitsubishi');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (43, 'Yellow Cab Man, The', 228.44, '2021-01-30', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 1.4, 'Nissan');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (44, 'Red Firecracker, Green Firecracker (Pao Da Shuang Deng)', 374.19, '2017-08-05', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 3.4, 'Subaru');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (45, 'Chronicle of My Mother (Waga haha no ki)', 322.02, '2019-12-14', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 9.7, 'Oldsmobile');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (46, 'Tristram Shandy: A Cock and Bull Story', 353.54, '2010-08-09', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 9.9, 'Mercedes-Benz');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (47, 'Rancho Deluxe', 310.96, '2017-04-10', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 6.6, 'Honda');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (48, 'Dead Men Don''t Wear Plaid', 186.66, '2016-11-04', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 5.0, 'Dodge');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (49, 'Quarantine', 117.79, '2012-10-13', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 8.9, 'Saab');
-- insert into product (id, Title, Price, ReleaseDate, Description, Rating, Platform) values (50, 'Lost Boys of Sudan', 58.18, '2016-12-26', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 3.0, 'BMW');